### PR TITLE
changed sanitizeWords to also take in a list of ignoredWords to filter out 

### PR DESCRIPTION
**Pull request by TruemanL**
(where the filtering occurs after converting words to lowercase) before stripping suffixes

Note that I've also hidden the filterWords function (it's now a private function accessible only in Parser)

### CODE REVIEW

**Comment by bolyachevets** [comment]
so by changing this you can avoid the problem of having a word "this" being stripped of suffix "s". You just filter "this" first, right?

What if we don't want to filter a word that ends with "s". For example "hypnosis". In theory we can maintain a list of words that we don't want to sanitize. But potentially we may need to introduce the list of words we want to strip of suffixes. For example. Compile a list of words that differ from each other only by the value of a suffix. 

For now, this is OK. But we should probably come back to this, if we have time and introduce the "on the fly" list creation that contains words to be sanitized based on variations present in either text or better unsanitized corpus.

**Comment by TruemanL** [comment]
Maybe we can introduce a list of stems that don't make any sense (nonsenseStems)? We can store this list in a file and add to it based on results from running our program on actual data?)

Ie. include as an input to sanitize words ("th", "hypnosi") so that if we were to strip "ing" from "thing" or "s" from "hypnosis", the resulting stem would match on this list of nonsenseStems and we would leave the word alone in this case?

**Comment by bolyachevets** [comment]
So, then we would need to verify every stem in the corpus against a dictionary to construct the short list of nonsensical stems?

**Comment by TruemanL** [comment]
I was thinking more of just a manual read through in person after a run to generate the corpus... how big do you think the corpus will get?

**Comment by bolyachevets** [comment]
Would be inefficient in real life. If we want to emulate some sort of practical solution, then either checking against corpus and blacklist as first step, then against dictionary (if no match found). The dictionary can be just a toy one for now.

**Comment by TruemanL** [comment]
ahh just did a bit of research in the last hour, maybe we can just use the haskell implementation of the Porter Stemming Algorithm and figure out how to cite it properly?
https://tartarus.org/martin/PorterStemmer/
https://tartarus.org/martin/PorterStemmer/haskell.txt

**Comment by bolyachevets** [comment]
That looks cool. Not sure if you just want to use the implementation, or built a simplified version of it.

**Comment by TruemanL** [comment]
i'll take a look at it once i get home, i can't run it on the computers at school because the base version of ghci they have here can't import Monad... but yea i'll probably just do some slight modifications to adapt it into our project but otherwise leave the internal logic alone.

**Pull request merged**
