### PR TITLE
Adapted porter stemmer algorithm into Parser

### PR DESCRIPTION
**Pull request by TruemanL**
Note the change in semantics to the parseGrams function. We no longer need to give the function a list of suffixes to remove. This means less flexibility for us but I think it's worth the extra thoroughness this tried-and-true algorithm provides.

### CODE REVIEW

**Comment by bolyachevets** [comment]
You may also fix parseGrams in Bag.hs

Do you think we can just add a whole copy-pasted file to the project?
Could we potentially just implement a simpler version of the algorithm ourselves

**Comment by TruemanL** [comment]
okay, i'll take care of Bag.hs as well.
And yes, i'm sure we're fine on using other people's code https://canvas.ubc.ca/courses/9395/discussion_topics/167554

that part just doesn't count towards the our contribution to the project.

**Comment by bolyachevets** [comment]
alright. this is fine then. but i am still thinking that its good to have this as a backup for potential contribution extension.

**Comment by TruemanL** [comment]
Sure, we don't have to write this off from our list of potential project extensions. But in the meantime i think it'll do a fine job for us. I've fixed Bag.hs' call to parseGrams now if you want to take a look. Note I've also changed the mock corpus you set up to reflect what the new stemming algorithm would produce.

**Pull request merged**
