### PR TITLE
Computing tf-idf values/vectors.

### PR DESCRIPTION
**Pull request by davidkarchynski**

### CODE REVIEW

**Comment by TruemanL** [comment]
Code looks clean, but I'm not too familiar with the logic you're trying to implement so maybe Andrew should give you the final okay for this.

In the mean-time, could you add a few test cases for each method (in comments for input examples and expected outputs like what we've got in the other files)? Both so it's easier for someone else to figure out what it's supposed to do and for us to make sure we don't break anything if we refactor or make other changes down the road?

**Comment by davidkarchynski** [comment]
@TruemanL Okay, I will add the test cases for the methods tomorrow and update the pr. In the meantime, @bolyachevets could you please take a look at the code / test output? Thanks!

**Comment by bolyachevets** [comment]
One immediate use of frequencies would be to get rid of the current process of filtering out some meaningless words (e.g., see the hardcoded list wordBlackList in Bag.hs). This is currently handled in the parser. What we want is to filter out the words based that have freq = fromIntegral totalOccurs * log(fromIntegral nDocs / fromIntegral totalOccurs) = 0 and expell them from our corpus. So, the filtering procedure needs to be changed to take advantage of this.

**Comment by davidkarchynski** [comment]
@bolyachevets Oh I see, I will incorporate the changes tomorrow and update the pr.

**Pull request merged**
